# Generated by Django 5.1.5 on 2025-01-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=1)),
                ("empresa", models.CharField(max_length=255)),
                ("responsable", models.CharField(max_length=255)),
                ("problematica", models.TextField()),
                ("servicios_realizados", models.TextField()),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_termino", models.TimeField()),
                (
                    "nivel_satisfaccion",
                    models.CharField(
                        choices=[
                            ("Malo", "Malo"),
                            ("Regular", "Regular"),
                            ("Bueno", "Bueno"),
                            ("Excelente", "Excelente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("problema_solucionado", models.BooleanField()),
                ("nombre_encargado", models.CharField(max_length=255)),
                ("nombre_cliente", models.CharField(max_length=255)),
                ("telefono_cliente", models.CharField(max_length=10)),
                (
                    "foto_inicio",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "foto_fin",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
            ],
        ),
    ]
