# Generated by Django 5.1.5 on 2025-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="nivel_satisfaccion",
            field=models.IntegerField(
                choices=[(1, "Malo"), (2, "Regular"), (3, "Bueno"), (4, "Excelente")]
            ),
        ),
    ]
