# Generated by Django 5.1.5 on 2025-01-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0002_alter_orden_nivel_satisfaccion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orden",
            old_name="fecha",
            new_name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="orden",
            name="fecha_finalizacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
