# Generated by Django 5.1.5 on 2025-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0003_rename_fecha_orden_fecha_inicio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="firma_cliente",
            field=models.ImageField(blank=True, null=True, upload_to="firmas/"),
        ),
        migrations.AddField(
            model_name="orden",
            name="firma_encargado",
            field=models.ImageField(blank=True, null=True, upload_to="firmas/"),
        ),
        migrations.AddField(
            model_name="orden",
            name="pdf_generado",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
