# Generated by Django 5.1.5 on 2025-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0004_orden_firma_cliente_orden_firma_encargado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="pdf_generado",
        ),
        migrations.AddField(
            model_name="orden",
            name="pdf_orden",
            field=models.FileField(blank=True, null=True, upload_to="ordenes_pdfs/"),
        ),
        migrations.AlterField(
            model_name="orden",
            name="empresa",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orden",
            name="firma_cliente",
            field=models.ImageField(
                blank=True, null=True, upload_to="firmas/clientes/"
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="firma_encargado",
            field=models.ImageField(
                blank=True, null=True, upload_to="firmas/encargados/"
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="foto_fin",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_finales/"),
        ),
        migrations.AlterField(
            model_name="orden",
            name="foto_inicio",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos_iniciales/"
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="identificador",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="orden",
            name="nombre_cliente",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orden",
            name="nombre_encargado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orden",
            name="responsable",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orden",
            name="telefono_cliente",
            field=models.CharField(max_length=15),
        ),
    ]
