# Generated by Django 5.1.5 on 2025-01-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0005_remove_orden_pdf_generado_orden_pdf_orden_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="firma_cliente",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="firma_encargado",
        ),
    ]
