# Generated by Django 5.1.5 on 2025-01-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DigitalFlow", "0007_remove_orden_pdf_orden_orden_pdf_generado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="nombre_cliente",
        ),
    ]
